"""add column readiness - table Orders

Revision ID: 3a93a1adff86
Revises: 41c178df41cd
Create Date: 2024-05-03 20:02:16.201836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a93a1adff86'
down_revision: Union[str, None] = '41c178df41cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('readiness', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'readiness')
    # ### end Alembic commands ###
