"""delete table collecting_cake.py

Revision ID: 41c178df41cd
Revises: ace57b3539fd
Create Date: 2024-05-01 22:16:45.068272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c178df41cd'
down_revision: Union[str, None] = 'ace57b3539fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collecting_cake')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collecting_cake',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=False),
    sa.Column('event', sa.VARCHAR(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='collecting_cake_cart_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='collecting_cake_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk__collecting_cake')
    )
    # ### end Alembic commands ###
