"""add clumn method to table User

Revision ID: 5f29a2bf20e8
Revises: dd34dcd5ba00
Create Date: 2024-04-21 17:51:45.207527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f29a2bf20e8'
down_revision: Union[str, None] = 'dd34dcd5ba00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('method', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'method')
    # ### end Alembic commands ###
